language: python
cache: pip
python:
  - "3.5"
  - "3.6"

env:
  - TEST_TYPE="test"
matrix:
  include:
    - python: 3.6
      env: TEST_TYPE="compliance"

install:
  - pip install -U pytest
  - pip install --process-dependency-links .[test]

script:
  - if [ "$TEST_TYPE" == "compliance" ] ; then pip install .[dev]; pre-commit run --all-files ; fi
  - if [ "$TEST_TYPE" == "test" ] ; then cd tests; pytest --no-plot-compare ; fi
